# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ce3d28ee669ed88c3cd1f42e57ed8d0bcdf85ac06787f46f8a09e58f7f7f6eeb73be9530bcd8475a7cc4b0e841f201e66d0d93b3c55b0ce85fa5df56e0782b

test:
  secret_key_base: 39c66596792558db3d2d318e986fe5247c7265e30924584dd24c71f810751008593995c61aada41ef9c0a8e1be8d65ce0b74ffa31222e748315f59b3e67aa00e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
